(defmacro test-equal (expr value)
  (let ((actual (gensym)))
    `(let ((,actual ,expr))
        (if (not (equal ,actual ,value))
          (progn
            (format-object (standard-output) ',expr t)
            (format-char (standard-output) #\newline)
            (format-object (standard-output) "Expect: " t)
            (format-object (standard-output) ,value nil)
            (format-char (standard-output) #\newline)
            (format-object (standard-output) "Actual: " t)
            (format-object (standard-output) ,actual nil)
            (format-char (standard-output) #\newline)
            (format-object (standard-output) "-------" nil)
            (format-char (standard-output) #\newline))))))

(let ((arr #2a((1 2) (3 4))))
  (test-equal (aref arr 0 0) 1)
  (test-equal (aref arr 0 1) 2)
  (test-equal (aref arr 1 0) 3)
  (test-equal (aref arr 1 1) 4))

(format-object (standard-output) "array.lisp end" nil)