(defun print (int)
    (format-integer (standard-output) int 10)
    (format-char (standard-output) #\newline))

(let ((p (cons 1 2)))
    (print (car p))
    (print (cdr p))
    (set-car 3 p)
    (set-cdr 4 p)
    (print (car p))
    (print (cdr p))
    (setf (car p) 5)
    (setf (cdr p) 6)
    (print (car p))
    (print (cdr p)))