(requires "testing.lisp")

(test-equal (floor  3.0) 3 )
(test-equal (floor  3.4) 3 )
(test-equal (floor  3.9) 3 )
(test-equal (floor -3.9) -4)
(test-equal (floor -3.4) -4)
(test-equal (floor -3.0) -3)

(test-equal (ceiling  3.0) 3 )
(test-equal (ceiling  3.4) 4 )
(test-equal (ceiling  3.9) 4 )
(test-equal (ceiling -3.9) -3)
(test-equal (ceiling -3.4) -3)
(test-equal (ceiling -3.0) -3)

(test-equal (truncate  3.0) 3 )
(test-equal (truncate  3.4) 3 )
(test-equal (truncate  3.9) 3 )
(test-equal (truncate -3.9) -3)
(test-equal (truncate -3.4) -3)
(test-equal (truncate -3.0) -3)

(test-equal (round  3.0) 3 )
(test-equal (round  3.4) 3 )
(test-equal (round  3.6) 4 )
(test-equal (round -3.6) -4)
(test-equal (round  3.5) 4 )
(test-equal (round -3.5) -4)
(test-equal (round  2.5) 2 )
(test-equal (round -0.5) 0 )

(format (standard-output) "rounding.lisp end")
(finish-output (standard-output))