(defun print (int)
    (format-integer (standard-output) int 10)
    (format-char (standard-output) #\newline))

(let ((v1 (vector 1 2))
      (v2 (create-vector 3 3))
      (v3 #(4 5)))
  (print (elt v1 0))
  (print (elt v2 0))
  (print (elt v3 0)))