= Truffle ISLISP reference.
:toc: left

Given that this is ISLISP implementation, primary reference is the http://www.islisp.org/ISLisp-spec.html[ISLISP 2007 specification]. This document details extensions and omissions made with respect to spec.

== Extensions

=== File operation extensions

Following extra functions are provided to complement standard file / stream api.

`(closed-p _stream_)`

Returns `t` if stream had been explicitly closed, `nil` otherwise. A `nil` result doesn't guarantee
the stream is operable.

`(delete-file _path-string_)`

Deletes a file a under given path string if it exists. It's not an error if it doesn't. Returns `nil`.


=== Module system

Truffle ISLISP provides a very simple module system, somewhat inspired by Racket. A module is colloquial to a file that defines its source.

Use `(requires _path-string_ ...)` to load modules; for example

[source,lisp]
----
(requires "lib/foo.lisp")
----

Use `(provides _symbol_ ...)` to define module's exports that will be used by modules that required it; for example

[source,lisp]
----
(provides public-function)

(defun public-function () (internal-function)) ;; only this function will be exported
(defun internal-function () "Hello world!")
----

The module paths are searched relative to sourcepath roots, which defaults to working directory. You can specify sourcepaths using `islisp.Sourcepath` (when using polyglot / embedding), or using `-sp` / `--sourcepath` when using standalone launcher. The value in both cases is root paths separated by system path separator.

For example; given the following files

[source]
----
root1/module1.lisp
root2/bar/module2.lisp
main.lisp
----

Where main.lisp starts with

[source,lisp]
----
(requires "module1.lisp" "bar/module2.lisp")
----

The correct invocation is `islisp -sp root1:root2 main.lisp` (on linux); `islisp -sp root1;root2 main.lisp` (on windows).

=== Debugger

`(debugger)` statement enables triggering debugger breakpoint from code. Works only when ran in debug mode. Returns nil.

=== Condition stacktraces

Conditions get stacktrace attached upon signalling by default. Stacktrace gather can be disabled for condition types by implementing method `(fill-stacktrace _condition-class_)` and returning nil from it.

Stacktrace can be inspected using generic method `(condition-stacktrace _condition_)`. A stacktrace is a vector of elements, where each element is itself a vector. Element's vector consists of: source name, start line, start column, end line, end column. Condition stacktraces are printed during `report-condition`. Stacktrace printing can be modified by changing dynamic variable `\*stacktrace-formatter*` and assigning it a formatter function which takes output stream as the first argument, stacktrace as the second, and writes necessary presentation to the stream.

=== Eval

You can eval any at runtime present truffle language code using `(eval _language-code_ _source-code_)`; for example

[source,lisp]
----
(let ((fun (eval "js" "(function(arg) { return 1 + arg; })")))
  (funcall fun 2)) ;; => 3
----

interop language's values are mapped to most fit ISLISP type. For some values, special procedures are given, see Truffle object api.

=== Truffle object interop API

External objects with fields are represented as instances of `<truffle-object>` class (which is subclass of `<object>`). You can get a vector of fields (as strings) in a given object using `(truffle-object-fields _truffle-obj_)`.

[source,lisp]
----
(let ((obj (eval "js" "{ a: 1}")))
  (truffle-object-fields obj)) ;; => #("a")
----

Use `(truffle-object-field _truffle-obj_ _field_)` to read a field of a truffle value.

Use `(truffle-object-set-field _value_ _truffle-obj_ _field_)` or `(setf (truffle-object-field _truffle-obj_ _field_) _value_)` to set a field value on a truffle object.

[source,lisp]
----
(let ((obj (eval "js" "({ a: 1 })")))
  (truffle-object-field obj "a") ;; => 1
  (setf (truffle-object-field obj "a") 2)
  (truffle-object-field obj "a")) ;; => 2
----

TODO: truffle interop conditions.

Interop arrays are presented as objects of class `<truffle-vector>`. The class extends`<basic-vector>` therefore the common vector / sequence methods can be used.

=== Native function interface

Truffle NFI internal language is provided through transparent interface. First, load the dynamic library using `(load-native-library _name_)`, which will return an object represented by class `<truffle-native-library>`. To extract a binding out of the library, call `(native-library-symbol _symbol-name_ _signature_)`. See https://www.graalvm.org/latest/graalvm-as-a-platform/language-implementation-framework/NFI/[truffle documentation] regarding details on how to define signature string.

[source,lisp]
----
(let* ((lib (load-native-library "libm.so.6"))
       (libm-sin (native-library-symbol lib "sin" "(DOUBLE):DOUBLE")))
  (funcall libm-sin 2.0)) ;; => ~ 0.909
----

=== Exit

Application can have early exit using `(exit _exit-code_)`, where exit-code is an integer.

== Omissions / spec violations.

* Alot of erronous calls don't raise appropriate conditions;

* Format to string functions won't track if they're on fresh line / the column index.