name: Build ISLISP site
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build_site.yml'
      - 'docs/**'
      - 'site/**'
jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Install dependencies'
        run: |
          sudo apt-get update
          sudo apt-get -y install asciidoctor
      - name: 'Build docs'
        run: |
          cd docs
          asciidoctor *.adoc
          cd ..
          cp docs/*.html site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
  deploy_site:
    needs: [build_site]
    if: ${{ startsWith(github.ref, 'refs/heads/master') }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4