name: Build ISLISP site
on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - 'site/**'
jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'site'
  deploy_site:
    needs: [build_site]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
