name: Test ISLISP
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Verify checkstyle
        run: |
          mvn validate
      - name: Test
        run: |
          mvn test
      - uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true
      - name: Build docker image
        run: |
          docker build . -t islisp
      - name: Extract built executable from docker
        run: |
          mkdir extract
          docker run --name temp-container-name --entrypoint sh islisp
          docker cp temp-container-name:/app/islisp extract
          docker rm temp-container-name
      - name: Upload executable to github nightly release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload nightly extract/islisp --clobber
