name: Test ISLISP
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Test
        run: |
          mvn test
      - name: Verify checkstyle
        run: |
          mvn validate
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name:
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: islisp